### ISSUE TITLE
package download is broken due to original exporter breaking changes (v0.13.0)

### ISSUE THREAD

**Issue by chebelom** [sbaerlocher/ansible.wmi_exporter#9]
Hi there,
thank you for this ansible role.
The installation now fails because it cannot find the file to download due to the original project breaking changes; the release-monitoring.org api call is still working though.

I am going to send you a pull request that fixes the url and filename for the packages.yml part soon.

thanks

**Comment by sbaerlocher** [comment]
It's done now.
